services:
  octopus:
    image: ghcr.io/xiaocqaq/octopus:latest
    ports:
       - '8080:8080'
    volumes:      
       - '/path/to/data:/app/data'
    container_name: octopus
    restart: unless-stopped
    network_mode: bridge
